### ISSUE TITLE
感谢这个项目, 同时对你修改的forkgram提问

### ISSUE THREAD

**Issue by crazypeace** [NyaMisty/cloudflare-workers-uniproxy#1]
感谢cloudflare-workers-uniproxy项目!

同时对你修改的forkgram项目提问, 抱歉那里没有issue.

----
我的目的: 我想让有@我的消息的群置顶显示.

我阅读了你的这篇
https://drafts.misty.moe/%E9%AD%94%E6%94%B9telegram--%E7%BE%A4%E7%BB%84%E5%86%85%E5%B1%8F%E8%94%BD-62d3b8cecea640059da1d12fe627dcd5
里面提到修改某些功能会让Telegram官方发ToS violation
我想问, 自己修改一下, 自己编译使用, 官方也要管吗? 官方管得到吗?
就像你实现的功能, 官方还是把消息发过来了, 我们只是在本地过滤了一下显示, 官方怎么知道的?

**Comment by NyaMisty** [comment]
可以的，我的建议是如果想杜绝封号还是冲一个tg会员，目前没见过tg premium被ban

**Comment by crazypeace** [comment]
哇, 感谢光速回复!
这个领域我确实从来没有涉足过. 也许问题会让你觉得奇怪, 先说声不好意思.

官方怎么知道你把群消息过滤了?  (1)
你修改了一版代码编译了, 官方知道你修改了哪些? (2)
你用(2)编译出来的程序登录了tg账号, 官方能把tg账号和代码对应起来? (3)
